---
kind: pipeline
name: omeka:3.0.2 php:7.4 mariadb:10.9
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.9
  name: db
steps:
- commands:
  - cp -rT /usr/src/omeka-s ../..
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: biblibre/omeka-s-ci:3.0.2-php7.4
  name: test
type: docker
workspace:
  path: omeka-s/modules/ItemSetsTree
---
kind: pipeline
name: omeka:3.1.2 php:8.0 mariadb:10.9
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.9
  name: db
steps:
- commands:
  - cp -rT /usr/src/omeka-s ../..
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: biblibre/omeka-s-ci:3.1.2-php8.0
  name: test
type: docker
workspace:
  path: omeka-s/modules/ItemSetsTree
---
kind: pipeline
name: omeka:3.2.3 php:8.0 mariadb:10.9
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.9
  name: db
steps:
- commands:
  - cp -rT /usr/src/omeka-s ../..
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: biblibre/omeka-s-ci:3.2.3-php8.0
  name: test
type: docker
workspace:
  path: omeka-s/modules/ItemSetsTree
---
kind: pipeline
name: omeka:4.0.0-rc php:8.0 mariadb:10.9
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.9
  name: db
steps:
- commands:
  - cp -rT /usr/src/omeka-s ../..
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: biblibre/omeka-s-ci:4.0.0-rc-php8.0
  name: test
type: docker
workspace:
  path: omeka-s/modules/ItemSetsTree
---
kind: pipeline
name: omeka:4.0.0-rc php:8.1 mariadb:10.9
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.9
  name: db
steps:
- commands:
  - cp -rT /usr/src/omeka-s ../..
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: biblibre/omeka-s-ci:4.0.0-rc-php8.1
  name: test
type: docker
workspace:
  path: omeka-s/modules/ItemSetsTree
---
kind: pipeline
name: documentation
steps:
- commands:
  - sh .drone/documentation-build.sh
  image: python:3
  name: build
- commands:
  - apk add git openssh
  - sh .drone/documentation-push.sh
  environment:
    GH_DEPLOY_KEY:
      from_secret: GH_DEPLOY_KEY
  image: alpine
  name: push
trigger:
  branch:
  - master
  event:
  - push
type: docker
---
kind: signature
hmac: 6761c631a6adb6a5e040504ba600e034a9be77755a3c6aeaa3d7e76bd2e2046e

...
