version: "3.3"

services:
  db:
    container_name: omeka_db
    image: mysql:8.3
    platform: linux/amd64
    ports:
      - "13306:3306"
    volumes:
      - .data/db:/var/lib/mysql:rw
      - ./docker/custom.cnf:/etc/mysql/conf.d/custom.cnf
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  omeka:
    #image:  docker.io/giocomai/omeka-s-docker:v3.2.3.production
    container_name: omeka
    build:
      context: .
      target: omeka
    platform: linux/arm64/v8
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./config:/var/www/html/config
      - ./files:/var/www/html/files
      - ./FileSideload_files:/FileSideload/files
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
    depends_on:
      - db