services:
  db:
    container_name: crossingfonds_db
    image: mariadb:10.11
    ports:
      - "13306:3306"
    volumes:
      - ./docker/custom.cnf:/etc/mysql/conf.d/custom.cnf
      # persistence
      - .data/db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: omeka
      MARIADB_USER: omeka
      MARIADB_PASSWORD: password
    healthcheck:
      test: mysql omeka -u omeka -ppassword -e 'SELECT 1;' || exit 1

  app:
    container_name: crossingfonds_app
    # image:  dhilsfu/crossingfonds
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./config:/var/www/html/config
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      # persistence
      - .data/files:/var/www/html/files
      - .data/FileSideload_files:/FileSideload/files
    depends_on:
      db:
        condition: service_healthy