<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Selection\Api\Representation\SelectionRepresentation $selection
 * // Helpers.
 * @var \Laminas\View\Helper\Url $url
 * @var \Omeka\View\Helper\I18n $i18n
 * @var \Laminas\View\Helper\EscapeHtml $escape
 * @var \Laminas\I18n\View\Helper\Translate $translate
 * @var \Omeka\View\Helper\Thumbnail $thumbnail
 * @var \Laminas\View\Helper\EscapeHtmlAttr $escapeAttr
 * // Static vars.
 * @var string $headingTerm
 * @var string $bodyTerm
 * @var array $defaultHeading
 * @var array $defaultBody
 * @var array $defaultLang
 * @var string $deleteText
 * @var string $moveText
 * // Individual resource.
 * @var string $resourceType
 * @var array $bulkExporters
 * @var \Omeka\Api\Representation\AbstractEntityRepresentation $resource
 */

// Partial loop template used by selection-resource-browse.

if (!$resource) return;

$resourceTypesToClasses = [
    'items' => 'item',
    'item_sets' => 'item-set',
    'media' => 'media',
    'annotations' => 'annotation',
    'resources' => 'resource',
];

$heading = $headingTerm ? $resource->value($headingTerm, $defaultHeading) : $resource->displayTitle(null, $defaultLang);
$body = $bodyTerm ? $resource->value($bodyTerm, $defaultBody) : $resource->displayDescription(null, $defaultLang);

// This is the base url, the query is added via js.
$baseUrl = pathinfo($url('site/selection-id', ['id' => $selection ? $selection->id() : 0, 'action' => '__'], true), PATHINFO_DIRNAME);
$resourceId = $resource->id();
$siteSlug = $site->slug();
?>

<li class="selection-resource resource <?= $resourceTypesToClasses[$resourceType] ?>" data-id="<?= $resourceId ?>">
    <?= $resource->linkRaw($thumbnail($resource, 'square'), null, ['class' => 'resource-link']) ?>
    <h4><?= $resource->link($heading) ?></h4>
    <?php if ($body): ?>
    <div class="description">
        <?= $body ?>
    </div>
    <?php endif; ?>
    <ul class="actions">
        <?php if ($selection && $selection->structure()): ?>
        <li><button type="button" class="move-resource" data-url="<?= $baseUrl ?>/move"><?= $moveText ?></button></li>
        <?php endif; ?>
        <li><button type="button" class="selection-delete" data-url="<?= $baseUrl ?>/delete"><?= $deleteText ?></button></li>
        <?php if ($bulkExporters):
        foreach ($bulkExporters as $format => $label):
            $urlFormat = $url('site/resource-id/output', ['site-slug' => $siteSlug, 'controller' => $resourceTypesToClasses[$resourceType], 'id' => $resourceId, 'action' => 'show', 'format' => $format]);
        ?>
        <li><a class="download-id" href="<?= $urlFormat ?>" download="download"><button type="button" class="export-group download-<?= $format ?>" data-url="<?= $urlFormat ?>"><?= $label ?></button></a></li>
        <?php endforeach; ?>
        <?php endif; ?>
    </ul>
</li>
