<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau 2018-2023
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Selection\Api\Representation\SelectionRepresentation $selection
 * @var \Selection\Api\Representation\SelectionResourceRepresentation[] $selectionResources
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var array $resourcesByType
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$partialLoop = $plugins->get('partialLoop');

// May be included in main layout.
$this->headLink()
    ->appendStylesheet($this->assetUrl('css/selection.css', 'Selection'));
$this->headScript()
    ->appendFile($this->assetUrl('js/selection.js', 'Selection'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'selection resource browse');

$lang = $this->lang();
$filterLocale = (bool) $siteSetting('filter_locale_values');
$headingTerm = $siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $siteSetting('browse_body_property_term', 'dcterms:description');
$bulkExporters = $plugins->has('bulkExporters') ? $plugins->get('bulkExporters')() : null;

$selectedResources = $selection ? $selection->resources() : [];

$classesToTypes = [
    \Omeka\Api\Representation\ItemRepresentation::class => 'items',
    \Omeka\Api\Representation\ItemSetRepresentation::class => 'item_sets',
    \Omeka\Api\Representation\MediaRepresentation::class => 'media',
    \Annotate\Api\Representation\AnnotationRepresentation::class => 'annotations',
];

// All data needed to display each selected resource quickly via partialLoop.
$selectedResourceModel = [
    'site' => $site,
    'selection' => $selection,
    'url' => $url,
    'i18n' => $i18n,
    'escape' => $escape,
    'translate' => $translate,
    'thumbnail' => $thumbnail,
    'escapeAttr' => $escapeAttr,
    'headingTerm' => $headingTerm,
    'bodyTerm' => $bodyTerm,
    'defaultHeading' => ['default' => $translate('[Untitled]'), 'lang' => ($filterLocale ? [$lang, ''] : null)],
    'defaultBody' => ['lang' => ($filterLocale ? [$lang, ''] : null)],
    'defaultLang' => $filterLocale ? [$lang, ''] : null,
    'moveText' => $escapeAttr($translate('Move')),
    'deleteText' => $escapeAttr($translate('Remove from selection')),
    'bulkExporters' => $bulkExporters,
    'resourceType' => null,
    'resource' => null,
];
?>

<?= $this->pageTitle($selection && ($label = $selection->label()) ? $label : $translate('Selection'), 2) ?>

<div class="selection-list selections">

    <?php if (count($selectionResources)): ?>
    <h3 class="selection-count"><?= sprintf($translate('%d items, %d media'), count($resourcesByType['items']), count($resourcesByType['media'])) ?></h3>
    <?php else: ?>
    <p class="selection-empty">
        <?= $translate('The selection is empty.') // @translate ?>
    </p>
    <?php endif; ?>

    <div class="selection-list-actions">
        <ul class="actions">
            <li>
                <button type="button" class="add-group" data-msg-group-name="<?= $translate('Set group name') ?>" data-url="<?= $url('site/selection-id', ['id' => $selection ? $selection->id() : 0, 'action' => 'add-group'], true) ?>"><?= $translate('Add a group') ?></button>
            </li>
        </ul>
    </div>

    <?php $this->trigger('view.browse.before'); ?>

    <?php // Groups and selected resources inside them. ?>
    <?php $templateGroup = $partial('guest/site/guest/selection-group'); ?>
    <ul class="resource-list selection-resources selection-structure" data-msg-add-group="<?= $translate('Set group name') ?>" data-template-group="<?= $escapeAttr($templateGroup) ?>">
        <?php
        foreach ($selection ? $selection->structure() : [] as $groupFullPath => $group):
            $selectedResourceModels = [];
            foreach ($group['resources'] ?? [] as $resourceId) {
                $resource = $selectedResources[$resourceId] ?? null;
                unset($selectedResources[$resourceId]);
                if (!$resource) continue;
                $selectedResourceModel['resource'] = $resource;
                $selectedResourceModel['resourceType'] = $classesToTypes[get_class($resource)] ?? 'resources';
                $selectedResourceModels[] = $selectedResourceModel;
            }
            $replace = [
                '__GROUP_LEVEL__' => substr_count($groupFullPath, '/'),
                '__GROUP_PATH__' => $escapeAttr($groupFullPath),
                '__GROUP_NAME__' => '<span>' . str_replace('/', '</span><span>', ltrim($groupFullPath, '/')) . '</span>',
                '__GROUP_RESOURCES__' => $selectedResourceModels
                    ? $partialLoop('guest/site/guest/selection-group-resource', $selectedResourceModels)
                    : '',
            ]; ?>
        <?= str_replace(array_keys($replace), array_values($replace), $templateGroup) ?>
        <?php endforeach; ?>
    </ul>

    <?php // Remaining selected resources without group. ?>
    <ul class="resource-list selection-resources">
        <?php
        $selectedResourceModels = [];
        foreach ($selectedResources  as $resourceId => $resource) {
            $selectedResourceModel['resource'] = $resource;
            $selectedResourceModel['resourceType'] = $classesToTypes[get_class($resource)] ?? 'resources';
            $selectedResourceModels[] = $selectedResourceModel;
        } ?>
        <?= $partialLoop('guest/site/guest/selection-group-resource', $selectedResourceModels) ?>
    </ul>
    <?php $this->trigger('view.browse.after'); ?>

</div>

<?php // Common actions. ?>
<div id="selector-group" class="selector-group inactive" style="display:none;">
    <select name="group" aria-label="<?= $translate('Select a group') ?>">
        <option value=""></option>
        <?php foreach ($selection ? array_keys($selection->structure()) : [] as $groupFullPath): ?>
        <option value="<?= $groupFullPath ?>"><?= str_replace('/', ' / ', $groupFullPath) ?></option>
        <?php endforeach ?>
    </select>
</div>
