<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var bool $selectionResource
 * @var string $url
 * and options passed from the caller.
 */

$translate = $this->plugin('translate');

$textSelect['unselected'] = $translate('Add to selection');
$textSelect['selected'] = $translate('Remove from selection');
$class = empty($selectionResource) ? 'unselected' : 'selected';
$text = $textSelect[$class];
?>

<button class="selection-update <?= $class ?>" data-id="<?= $resource->id() ?>" title="<?= $text ?>" data-title-selected="<?= $textSelect['selected'] ?>" data-title-unselected="<?= $textSelect['unselected'] ?>" data-url="<?= $url ?>">
    <span class="fas fa-bookmark"></span >
</button>
