<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User|null $user
 * @var \Contribute\Form\ContributeForm $form
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var array $fields
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation $templateMedia A sub template for media may have no fields.
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit" or "show"
 * @var string $mode "read" (for template select or for show readonly form before submit) or "write"
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$contributionForm = $plugins->get('contributionForm');

$this->htmlElement('body')->appendAttribute('class', 'edit items ' . $this->params()->fromRoute('resource') . ' resource');

if ($form) $form->prepare();

$mapLabels = [
    'contributions' => 'item',
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="contribute-resource conbribute-add container <?= $space && $space !== 'default' ? $space : '' ?>">

    
    <h3><?= $resource ? sprintf($translate('Contributing metadata to:'), $translate($mapLabels[$resource->resourceName()])) : sprintf($translate('New %s'), $translate($mapLabels['items'])) ?> <?= $this->pageTitle($resource ? $escape($resource->displayTitle()) : sprintf($translate('Add %s'), $translate($mapLabels['items'])), 2) ?></h3>

    <div class="guide"> 
        <p>Welcome to the contribution page! Here you can submit new metadata through several different databases for controlled vocabulary. 
        <br><br> To attach a new metadata value, choose your prefered vocabulary and click "Add linked data" to open a text field. Once you have entered your suggestion, a list of options will generate (please allow a moment for the list to populate). Click to select your chosen value. 
        To contribute more metadata, select "Add linked data" again, either for the same vocabulary or a different one.
        Click submit at the bottom of the page when done. Pending admin approval, your metadata contribution will be added to the item. </p>
    </div>

    <br>
    <br>

    <h3>Vocabularies:</h3>

    <div class="messages">
        <?= $this->messages() ?>
    </div>

    <?php if (count($fields) && $form):
        // The two lists of fields are merged in one form by default.
        $this->trigger("view.$action.before");
        echo $contributionForm([
            'site' => $site,
            'user' => $user,
            'form' => $form,
            'contribution' => $contribution,
            'resource' => $resource,
            'fields' => $fields,
            'templateMedia' => $templateMedia,
            'fieldsByMedia' => $fieldsByMedia,
            'fieldsMediaBase' => $fieldsMediaBase,
            'action' => $action,
            'mode' => $mode,
            'space' => $space,
            'submitLabel' => $action === 'add' && $setting('contribute_allow_update') !== 'no' ? $translate('Add') : $translate('Submit'),
            'cancelLabel' => $translate('Cancel'),
            'isMainForm' => true,
            'skipContributeCss' => false,
        ]);
        $this->trigger("view.$action.after");

    elseif ($action === 'add' && $form): // First step form to select a resource template.
        if ($mode === 'read') {
            $form->remove('submit');
            echo $this->form($form);
        } else {
            $form->get('submit')->setValue('Select'); // @translate
            echo $this->form($form);
        }

    else: ?>
    <div class="messages">
        <p><?= $translate('A template with fields is required to submit a document. Ask the administrator for more information.') ?></p>
    </div>

    <?php endif; ?>

</div>
